import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/hero-section/hero-section'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<HeroSection />
			</main>
		</div>
	)
}

export default Home
